services:
  vaultwarden:
    image: vaultwarden/server:1.30.5
    container_name: vaultwarden
    restart: unless-stopped
    ports:
      - "8443:8443"
    volumes:
      - vaultwarden_data:/data
      - C:/Users/danie/vaultwarden/localhost.pem:/ssl/localhost.pem
      - C:/Users/danie/vaultwarden/localhost-key.pem:/ssl/localhost-key.pem
    environment:
      - SIGNUPS_ALLOWED=true
      - DOMAIN=https://localhost:8443
      - ROCKET_PORT=8443
      - ROCKET_TLS={certs="/ssl/localhost.pem",key="/ssl/localhost-key.pem"}

volumes:
  vaultwarden_data: